--No15-8.FORMAT_ERROR_BACKTRACE
SET SERVEROUTPUT ON
DECLARE
  PROCEDURE p IS
  BEGIN    
    RAISE_APPLICATION_ERROR(-20001, '使用者指定EXCEPTION');
  END;
BEGIN
  p;
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;


--以下、結果

--SQL> @C:\kim\tech\plsql\Chapter15\No15_8.sql
-- 24  /
--ORA-20001: 使用者指定EXCEPTION
--ORA-06512: 行4
--ORA-06512: 行7
--
--
--
--PL/SQLプロシージャが正常に完了しました。
--
--SQL>